name: Security
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  scan:
    uses: SiLaX49/workflows/.github/workflows/security-scan.yml@main
